### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Krutonium** [PuttItOut/.netVoatApiWrapper#2]
Error   1   'VoatApiWrapper.VoatApiProxy' does not contain a definition for 'PostDiscussion' and no extension method 'PostDiscussion' accepting a first argument of type 'VoatApiWrapper.VoatApiProxy' could be found (are you missing a using directive or an assembly reference?) C:\Users\pfckr\Source\Repos.netVoatApiWrapper\VoatApiWrapper\Harness\Program.cs    46  28  Harness

Error   2   No overload for method 'GetUserComments' takes 1 arguments  C:\Users\pfckr\Source\Repos.netVoatApiWrapper\VoatApiWrapper\Harness\Program.cs    66  24  Harness

Visual Studio 2013

**Comment by PuttItOut** [comment]
Yeah, my bad. Been so busy haven't had time to merge a PR. Doing that now.

Apologies.

**Comment by Krutonium** [comment]
NP :P

**Comment by Krutonium** [comment]
Can I recommend using a CI like what I use on https://github.com/PFCKrutonium/OpenRCT2Launcher ?
